# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

react_native_path = '../react-native/node_modules/react-native'
node_modules_path = '../react-native/node_modules'

target 'BottomTest' do
 pod 'React', :path => react_native_path, :subspecs =>
    [
       'Core',
       'CxxBridge',
       'DevSupport',
       'RCTActionSheet',
       'RCTGeolocation',
       'RCTImage',
       'RCTNetwork',
       'RCTPushNotification',
       'RCTSettings',
       'RCTText',
       'RCTVibration',
       'RCTWebSocket',
       'RCTAnimation',
       'RCTBlob',
       'RCTLinkingIOS',
       ]
    pod'yoga', :path => react_native_path + '/ReactCommon/yoga'
    pod'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
    pod'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
    pod'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
    pod'RNGestureHandler', :path => node_modules_path + '/react-native-gesture-handler'
    pod'CodePush', :path => node_modules_path + '/react-native-code-push'
    
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BottomTest

  target 'BottomTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BottomTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
